window.esdocSearchIndex = [
  [
    "@aureooms/js-fliplist/src/old/direction.js~direction",
    "class/src/old/Direction.js~Direction.html",
    "<span>Direction</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/old/Direction.js</span>",
    "class"
  ],
  [
    "@aureooms/js-fliplist/src/fliplist.js~fliplist",
    "class/src/FlipList.js~FlipList.html",
    "<span>FlipList</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/FlipList.js</span>",
    "class"
  ],
  [
    "@aureooms/js-fliplist/src/old/fliplist.js~fliplist",
    "class/src/old/FlipList.js~FlipList.html",
    "<span>FlipList</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/old/FlipList.js</span>",
    "class"
  ],
  [
    "@aureooms/js-fliplist/src/old/endpointiterator.js~headiterator",
    "class/src/old/EndpointIterator.js~HeadIterator.html",
    "<span>HeadIterator</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/old/EndpointIterator.js</span>",
    "class"
  ],
  [
    "@aureooms/js-fliplist/src/old/iterator2.js~iterator2",
    "class/src/old/Iterator2.js~Iterator2.html",
    "<span>Iterator2</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/old/Iterator2.js</span>",
    "class"
  ],
  [
    "@aureooms/js-fliplist/src/iterator.js~iterator",
    "class/src/Iterator.js~Iterator.html",
    "<span>Iterator</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/Iterator.js</span>",
    "class"
  ],
  [
    "@aureooms/js-fliplist/src/old/iterator3.js~iterator",
    "class/src/old/Iterator3.js~Iterator.html",
    "<span>Iterator</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/old/Iterator3.js</span>",
    "class"
  ],
  [
    "@aureooms/js-fliplist/src/node.js~node",
    "class/src/Node.js~Node.html",
    "<span>Node</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/Node.js</span>",
    "class"
  ],
  [
    "@aureooms/js-fliplist/src/old/node.js~node",
    "class/src/old/Node.js~Node.html",
    "<span>Node</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/old/Node.js</span>",
    "class"
  ],
  [
    "@aureooms/js-fliplist/src/old/reverseiterator.js~reverseiterator",
    "class/src/old/ReverseIterator.js~ReverseIterator.html",
    "<span>ReverseIterator</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/old/ReverseIterator.js</span>",
    "class"
  ],
  [
    "@aureooms/js-fliplist/src/old/internaliterator.js~reversibleinternaliterator",
    "class/src/old/InternalIterator.js~ReversibleInternalIterator.html",
    "<span>ReversibleInternalIterator</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/old/InternalIterator.js</span>",
    "class"
  ],
  [
    "@aureooms/js-fliplist/src/old/validitytoken.js~validitytoken",
    "class/src/old/ValidityToken.js~ValidityToken.html",
    "<span>ValidityToken</span> <span class=\"search-result-import-path\">@aureooms/js-fliplist/src/old/ValidityToken.js</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/fliplist.js",
    "file/src/FlipList.js.html",
    "src/FlipList.js",
    "file"
  ],
  [
    "src/fliplist.js~fliplist#[symbol.iterator]",
    "class/src/FlipList.js~FlipList.html#instance-method-[Symbol.iterator]",
    "src/FlipList.js~FlipList#[Symbol.iterator]",
    "method"
  ],
  [
    "src/fliplist.js~fliplist#append",
    "class/src/FlipList.js~FlipList.html#instance-method-append",
    "src/FlipList.js~FlipList#append",
    "method"
  ],
  [
    "src/fliplist.js~fliplist#begin",
    "class/src/FlipList.js~FlipList.html#instance-method-begin",
    "src/FlipList.js~FlipList#begin",
    "method"
  ],
  [
    "src/fliplist.js~fliplist#constructor",
    "class/src/FlipList.js~FlipList.html#instance-constructor-constructor",
    "src/FlipList.js~FlipList#constructor",
    "method"
  ],
  [
    "src/fliplist.js~fliplist#end",
    "class/src/FlipList.js~FlipList.html#instance-method-end",
    "src/FlipList.js~FlipList#end",
    "method"
  ],
  [
    "src/fliplist.js~fliplist#extend",
    "class/src/FlipList.js~FlipList.html#instance-method-extend",
    "src/FlipList.js~FlipList#extend",
    "method"
  ],
  [
    "src/fliplist.js~fliplist#head",
    "class/src/FlipList.js~FlipList.html#instance-member-head",
    "src/FlipList.js~FlipList#head",
    "member"
  ],
  [
    "src/fliplist.js~fliplist#prepend",
    "class/src/FlipList.js~FlipList.html#instance-method-prepend",
    "src/FlipList.js~FlipList#prepend",
    "method"
  ],
  [
    "src/fliplist.js~fliplist#rbegin",
    "class/src/FlipList.js~FlipList.html#instance-method-rbegin",
    "src/FlipList.js~FlipList#rbegin",
    "method"
  ],
  [
    "src/fliplist.js~fliplist#rend",
    "class/src/FlipList.js~FlipList.html#instance-method-rend",
    "src/FlipList.js~FlipList#rend",
    "method"
  ],
  [
    "src/fliplist.js~fliplist#reverse",
    "class/src/FlipList.js~FlipList.html#instance-method-reverse",
    "src/FlipList.js~FlipList#reverse",
    "method"
  ],
  [
    "src/fliplist.js~fliplist#reversebetween",
    "class/src/FlipList.js~FlipList.html#instance-method-reversebetween",
    "src/FlipList.js~FlipList#reversebetween",
    "method"
  ],
  [
    "src/fliplist.js~fliplist#rhead",
    "class/src/FlipList.js~FlipList.html#instance-member-rhead",
    "src/FlipList.js~FlipList#rhead",
    "member"
  ],
  [
    "src/fliplist.js~fliplist#rtail",
    "class/src/FlipList.js~FlipList.html#instance-member-rtail",
    "src/FlipList.js~FlipList#rtail",
    "member"
  ],
  [
    "src/fliplist.js~fliplist#tail",
    "class/src/FlipList.js~FlipList.html#instance-member-tail",
    "src/FlipList.js~FlipList#tail",
    "member"
  ],
  [
    "src/iterator.js",
    "file/src/Iterator.js.html",
    "src/Iterator.js",
    "file"
  ],
  [
    "src/iterator.js~iterator#constructor",
    "class/src/Iterator.js~Iterator.html#instance-constructor-constructor",
    "src/Iterator.js~Iterator#constructor",
    "method"
  ],
  [
    "src/iterator.js~iterator#next",
    "class/src/Iterator.js~Iterator.html#instance-method-next",
    "src/Iterator.js~Iterator#next",
    "method"
  ],
  [
    "src/iterator.js~iterator#node",
    "class/src/Iterator.js~Iterator.html#instance-member-node",
    "src/Iterator.js~Iterator#node",
    "member"
  ],
  [
    "src/iterator.js~iterator#prev",
    "class/src/Iterator.js~Iterator.html#instance-method-prev",
    "src/Iterator.js~Iterator#prev",
    "method"
  ],
  [
    "src/iterator.js~iterator#reversed",
    "class/src/Iterator.js~Iterator.html#instance-method-reversed",
    "src/Iterator.js~Iterator#reversed",
    "method"
  ],
  [
    "src/iterator.js~iterator#rewind",
    "class/src/Iterator.js~Iterator.html#instance-method-rewind",
    "src/Iterator.js~Iterator#rewind",
    "method"
  ],
  [
    "src/iterator.js~iterator#skip",
    "class/src/Iterator.js~Iterator.html#instance-method-skip",
    "src/Iterator.js~Iterator#skip",
    "method"
  ],
  [
    "src/iterator.js~iterator#value",
    "class/src/Iterator.js~Iterator.html#instance-method-value",
    "src/Iterator.js~Iterator#value",
    "method"
  ],
  [
    "src/node.js",
    "file/src/Node.js.html",
    "src/Node.js",
    "file"
  ],
  [
    "src/node.js~node#constructor",
    "class/src/Node.js~Node.html#instance-constructor-constructor",
    "src/Node.js~Node#constructor",
    "method"
  ],
  [
    "src/node.js~node#next",
    "class/src/Node.js~Node.html#instance-member-next",
    "src/Node.js~Node#next",
    "member"
  ],
  [
    "src/node.js~node#sibling",
    "class/src/Node.js~Node.html#instance-member-sibling",
    "src/Node.js~Node#sibling",
    "member"
  ],
  [
    "src/node.js~node#value",
    "class/src/Node.js~Node.html#instance-member-value",
    "src/Node.js~Node#value",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/old/direction.js",
    "file/src/old/Direction.js.html",
    "src/old/Direction.js",
    "file"
  ],
  [
    "src/old/direction.js~direction#constructor",
    "class/src/old/Direction.js~Direction.html#instance-constructor-constructor",
    "src/old/Direction.js~Direction#constructor",
    "method"
  ],
  [
    "src/old/direction.js~direction#reversed",
    "class/src/old/Direction.js~Direction.html#instance-member-reversed",
    "src/old/Direction.js~Direction#reversed",
    "member"
  ],
  [
    "src/old/endpointiterator.js",
    "file/src/old/EndpointIterator.js.html",
    "src/old/EndpointIterator.js",
    "file"
  ],
  [
    "src/old/endpointiterator.js~headiterator#constructor",
    "class/src/old/EndpointIterator.js~HeadIterator.html#instance-constructor-constructor",
    "src/old/EndpointIterator.js~HeadIterator#constructor",
    "method"
  ],
  [
    "src/old/endpointiterator.js~headiterator#direction",
    "class/src/old/EndpointIterator.js~HeadIterator.html#instance-member-direction",
    "src/old/EndpointIterator.js~HeadIterator#direction",
    "member"
  ],
  [
    "src/old/endpointiterator.js~headiterator#done",
    "class/src/old/EndpointIterator.js~HeadIterator.html#instance-member-done",
    "src/old/EndpointIterator.js~HeadIterator#done",
    "member"
  ],
  [
    "src/old/endpointiterator.js~headiterator#next",
    "class/src/old/EndpointIterator.js~HeadIterator.html#instance-method-next",
    "src/old/EndpointIterator.js~HeadIterator#next",
    "method"
  ],
  [
    "src/old/endpointiterator.js~headiterator#node",
    "class/src/old/EndpointIterator.js~HeadIterator.html#instance-member-node",
    "src/old/EndpointIterator.js~HeadIterator#node",
    "member"
  ],
  [
    "src/old/endpointiterator.js~headiterator#valid",
    "class/src/old/EndpointIterator.js~HeadIterator.html#instance-method-valid",
    "src/old/EndpointIterator.js~HeadIterator#valid",
    "method"
  ],
  [
    "src/old/endpointiterator.js~headiterator#validity",
    "class/src/old/EndpointIterator.js~HeadIterator.html#instance-member-validity",
    "src/old/EndpointIterator.js~HeadIterator#validity",
    "member"
  ],
  [
    "src/old/endpointiterator.js~headiterator#value",
    "class/src/old/EndpointIterator.js~HeadIterator.html#instance-member-value",
    "src/old/EndpointIterator.js~HeadIterator#value",
    "member"
  ],
  [
    "src/old/fliplist.js",
    "file/src/old/FlipList.js.html",
    "src/old/FlipList.js",
    "file"
  ],
  [
    "src/old/fliplist.js~fliplist#append",
    "class/src/old/FlipList.js~FlipList.html#instance-method-append",
    "src/old/FlipList.js~FlipList#append",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#bd",
    "class/src/old/FlipList.js~FlipList.html#instance-member-bd",
    "src/old/FlipList.js~FlipList#bd",
    "member"
  ],
  [
    "src/old/fliplist.js~fliplist#begin",
    "class/src/old/FlipList.js~FlipList.html#instance-method-begin",
    "src/old/FlipList.js~FlipList#begin",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#constructor",
    "class/src/old/FlipList.js~FlipList.html#instance-constructor-constructor",
    "src/old/FlipList.js~FlipList#constructor",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#end",
    "class/src/old/FlipList.js~FlipList.html#instance-method-end",
    "src/old/FlipList.js~FlipList#end",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#extend",
    "class/src/old/FlipList.js~FlipList.html#instance-method-extend",
    "src/old/FlipList.js~FlipList#extend",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#fd",
    "class/src/old/FlipList.js~FlipList.html#instance-member-fd",
    "src/old/FlipList.js~FlipList#fd",
    "member"
  ],
  [
    "src/old/fliplist.js~fliplist#first",
    "class/src/old/FlipList.js~FlipList.html#instance-method-first",
    "src/old/FlipList.js~FlipList#first",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#head",
    "class/src/old/FlipList.js~FlipList.html#instance-member-head",
    "src/old/FlipList.js~FlipList#head",
    "member"
  ],
  [
    "src/old/fliplist.js~fliplist#insert_after",
    "class/src/old/FlipList.js~FlipList.html#instance-method-insert_after",
    "src/old/FlipList.js~FlipList#insert_after",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#insert_before",
    "class/src/old/FlipList.js~FlipList.html#instance-method-insert_before",
    "src/old/FlipList.js~FlipList#insert_before",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#last",
    "class/src/old/FlipList.js~FlipList.html#instance-method-last",
    "src/old/FlipList.js~FlipList#last",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#prepend",
    "class/src/old/FlipList.js~FlipList.html#instance-method-prepend",
    "src/old/FlipList.js~FlipList#prepend",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#rbegin",
    "class/src/old/FlipList.js~FlipList.html#instance-method-rbegin",
    "src/old/FlipList.js~FlipList#rbegin",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#rend",
    "class/src/old/FlipList.js~FlipList.html#instance-method-rend",
    "src/old/FlipList.js~FlipList#rend",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#reverse",
    "class/src/old/FlipList.js~FlipList.html#instance-method-reverse",
    "src/old/FlipList.js~FlipList#reverse",
    "method"
  ],
  [
    "src/old/fliplist.js~fliplist#reversed",
    "class/src/old/FlipList.js~FlipList.html#instance-member-reversed",
    "src/old/FlipList.js~FlipList#reversed",
    "member"
  ],
  [
    "src/old/fliplist.js~fliplist#tail",
    "class/src/old/FlipList.js~FlipList.html#instance-member-tail",
    "src/old/FlipList.js~FlipList#tail",
    "member"
  ],
  [
    "src/old/fliplist.js~fliplist#validity",
    "class/src/old/FlipList.js~FlipList.html#instance-member-validity",
    "src/old/FlipList.js~FlipList#validity",
    "member"
  ],
  [
    "src/old/internaliterator.js",
    "file/src/old/InternalIterator.js.html",
    "src/old/InternalIterator.js",
    "file"
  ],
  [
    "src/old/internaliterator.js~reversibleinternaliterator#constructor",
    "class/src/old/InternalIterator.js~ReversibleInternalIterator.html#instance-constructor-constructor",
    "src/old/InternalIterator.js~ReversibleInternalIterator#constructor",
    "method"
  ],
  [
    "src/old/internaliterator.js~reversibleinternaliterator#direction",
    "class/src/old/InternalIterator.js~ReversibleInternalIterator.html#instance-member-direction",
    "src/old/InternalIterator.js~ReversibleInternalIterator#direction",
    "member"
  ],
  [
    "src/old/internaliterator.js~reversibleinternaliterator#done",
    "class/src/old/InternalIterator.js~ReversibleInternalIterator.html#instance-member-done",
    "src/old/InternalIterator.js~ReversibleInternalIterator#done",
    "member"
  ],
  [
    "src/old/internaliterator.js~reversibleinternaliterator#next",
    "class/src/old/InternalIterator.js~ReversibleInternalIterator.html#instance-method-next",
    "src/old/InternalIterator.js~ReversibleInternalIterator#next",
    "method"
  ],
  [
    "src/old/internaliterator.js~reversibleinternaliterator#node",
    "class/src/old/InternalIterator.js~ReversibleInternalIterator.html#instance-member-node",
    "src/old/InternalIterator.js~ReversibleInternalIterator#node",
    "member"
  ],
  [
    "src/old/internaliterator.js~reversibleinternaliterator#pred",
    "class/src/old/InternalIterator.js~ReversibleInternalIterator.html#instance-member-pred",
    "src/old/InternalIterator.js~ReversibleInternalIterator#pred",
    "member"
  ],
  [
    "src/old/internaliterator.js~reversibleinternaliterator#succ",
    "class/src/old/InternalIterator.js~ReversibleInternalIterator.html#instance-member-succ",
    "src/old/InternalIterator.js~ReversibleInternalIterator#succ",
    "member"
  ],
  [
    "src/old/internaliterator.js~reversibleinternaliterator#valid",
    "class/src/old/InternalIterator.js~ReversibleInternalIterator.html#instance-method-valid",
    "src/old/InternalIterator.js~ReversibleInternalIterator#valid",
    "method"
  ],
  [
    "src/old/internaliterator.js~reversibleinternaliterator#validity",
    "class/src/old/InternalIterator.js~ReversibleInternalIterator.html#instance-member-validity",
    "src/old/InternalIterator.js~ReversibleInternalIterator#validity",
    "member"
  ],
  [
    "src/old/internaliterator.js~reversibleinternaliterator#value",
    "class/src/old/InternalIterator.js~ReversibleInternalIterator.html#instance-member-value",
    "src/old/InternalIterator.js~ReversibleInternalIterator#value",
    "member"
  ],
  [
    "src/old/iterator2.js",
    "file/src/old/Iterator2.js.html",
    "src/old/Iterator2.js",
    "file"
  ],
  [
    "src/old/iterator2.js~iterator2#constructor",
    "class/src/old/Iterator2.js~Iterator2.html#instance-constructor-constructor",
    "src/old/Iterator2.js~Iterator2#constructor",
    "method"
  ],
  [
    "src/old/iterator2.js~iterator2#direction",
    "class/src/old/Iterator2.js~Iterator2.html#instance-member-direction",
    "src/old/Iterator2.js~Iterator2#direction",
    "member"
  ],
  [
    "src/old/iterator2.js~iterator2#done",
    "class/src/old/Iterator2.js~Iterator2.html#instance-member-done",
    "src/old/Iterator2.js~Iterator2#done",
    "member"
  ],
  [
    "src/old/iterator2.js~iterator2#next",
    "class/src/old/Iterator2.js~Iterator2.html#instance-method-next",
    "src/old/Iterator2.js~Iterator2#next",
    "method"
  ],
  [
    "src/old/iterator2.js~iterator2#node",
    "class/src/old/Iterator2.js~Iterator2.html#instance-member-node",
    "src/old/Iterator2.js~Iterator2#node",
    "member"
  ],
  [
    "src/old/iterator2.js~iterator2#value",
    "class/src/old/Iterator2.js~Iterator2.html#instance-member-value",
    "src/old/Iterator2.js~Iterator2#value",
    "member"
  ],
  [
    "src/old/iterator3.js",
    "file/src/old/Iterator3.js.html",
    "src/old/Iterator3.js",
    "file"
  ],
  [
    "src/old/iterator3.js~iterator#constructor",
    "class/src/old/Iterator3.js~Iterator.html#instance-constructor-constructor",
    "src/old/Iterator3.js~Iterator#constructor",
    "method"
  ],
  [
    "src/old/iterator3.js~iterator#direction",
    "class/src/old/Iterator3.js~Iterator.html#instance-member-direction",
    "src/old/Iterator3.js~Iterator#direction",
    "member"
  ],
  [
    "src/old/iterator3.js~iterator#done",
    "class/src/old/Iterator3.js~Iterator.html#instance-member-done",
    "src/old/Iterator3.js~Iterator#done",
    "member"
  ],
  [
    "src/old/iterator3.js~iterator#next",
    "class/src/old/Iterator3.js~Iterator.html#instance-method-next",
    "src/old/Iterator3.js~Iterator#next",
    "method"
  ],
  [
    "src/old/iterator3.js~iterator#node",
    "class/src/old/Iterator3.js~Iterator.html#instance-member-node",
    "src/old/Iterator3.js~Iterator#node",
    "member"
  ],
  [
    "src/old/iterator3.js~iterator#value",
    "class/src/old/Iterator3.js~Iterator.html#instance-member-value",
    "src/old/Iterator3.js~Iterator#value",
    "member"
  ],
  [
    "src/old/node.js",
    "file/src/old/Node.js.html",
    "src/old/Node.js",
    "file"
  ],
  [
    "src/old/node.js~node#bw",
    "class/src/old/Node.js~Node.html#instance-member-bw",
    "src/old/Node.js~Node#bw",
    "member"
  ],
  [
    "src/old/node.js~node#constructor",
    "class/src/old/Node.js~Node.html#instance-constructor-constructor",
    "src/old/Node.js~Node#constructor",
    "method"
  ],
  [
    "src/old/node.js~node#fw",
    "class/src/old/Node.js~Node.html#instance-member-fw",
    "src/old/Node.js~Node#fw",
    "member"
  ],
  [
    "src/old/node.js~node#value",
    "class/src/old/Node.js~Node.html#instance-member-value",
    "src/old/Node.js~Node#value",
    "member"
  ],
  [
    "src/old/reverseiterator.js",
    "file/src/old/ReverseIterator.js.html",
    "src/old/ReverseIterator.js",
    "file"
  ],
  [
    "src/old/reverseiterator.js~reverseiterator#constructor",
    "class/src/old/ReverseIterator.js~ReverseIterator.html#instance-constructor-constructor",
    "src/old/ReverseIterator.js~ReverseIterator#constructor",
    "method"
  ],
  [
    "src/old/reverseiterator.js~reverseiterator#current",
    "class/src/old/ReverseIterator.js~ReverseIterator.html#instance-member-current",
    "src/old/ReverseIterator.js~ReverseIterator#current",
    "member"
  ],
  [
    "src/old/reverseiterator.js~reverseiterator#done",
    "class/src/old/ReverseIterator.js~ReverseIterator.html#instance-member-done",
    "src/old/ReverseIterator.js~ReverseIterator#done",
    "member"
  ],
  [
    "src/old/reverseiterator.js~reverseiterator#next",
    "class/src/old/ReverseIterator.js~ReverseIterator.html#instance-method-next",
    "src/old/ReverseIterator.js~ReverseIterator#next",
    "method"
  ],
  [
    "src/old/reverseiterator.js~reverseiterator#parent",
    "class/src/old/ReverseIterator.js~ReverseIterator.html#instance-member-parent",
    "src/old/ReverseIterator.js~ReverseIterator#parent",
    "member"
  ],
  [
    "src/old/reverseiterator.js~reverseiterator#valid",
    "class/src/old/ReverseIterator.js~ReverseIterator.html#instance-method-valid",
    "src/old/ReverseIterator.js~ReverseIterator#valid",
    "method"
  ],
  [
    "src/old/reverseiterator.js~reverseiterator#value",
    "class/src/old/ReverseIterator.js~ReverseIterator.html#instance-member-value",
    "src/old/ReverseIterator.js~ReverseIterator#value",
    "member"
  ],
  [
    "src/old/validitytoken.js",
    "file/src/old/ValidityToken.js.html",
    "src/old/ValidityToken.js",
    "file"
  ],
  [
    "src/old/validitytoken.js~validitytoken#constructor",
    "class/src/old/ValidityToken.js~ValidityToken.html#instance-constructor-constructor",
    "src/old/ValidityToken.js~ValidityToken#constructor",
    "method"
  ],
  [
    "src/old/validitytoken.js~validitytoken#valid",
    "class/src/old/ValidityToken.js~ValidityToken.html#instance-member-valid",
    "src/old/ValidityToken.js~ValidityToken#valid",
    "member"
  ]
]